version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/docker/volumes/jenkins:/var/jenkins_home
    container_name: mellmo-jenkins
    environment:
      - VIRTUAL_HOST=jenkins.localhos

