version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2375:2375"
    volumes:
      - ${JENKINS_CONTAINER_VOLUME}:/var/jenkins_home
    container_name: ${JENKINS_CONTAINER_NAME}
    environment:
      - VIRTUAL_HOST=${JENKINS_CONTAINER_VIRTUALHOST}
